#!/usr/bin/env python3
"""Convert black-and-white PNGs into the right-hand nice!view art (LVGL 1-bit C file).

    python3 scripts/nice_view_art.py doom=art/doom_mask.png:bottom kunteynir=art/kunteynir.png:center

Each NAME=PNG[:align] becomes `const lv_img_dsc_t NAME` in widgets/art.c; the picture shown is
picked in Kconfig (NICE_VIEW_DOOM_ART_*). --preview DIR writes NAME.png screen previews there.

The art area under the battery strip is 68 px wide and 140 px tall (keyboard held normally).
Light pixels in the PNG are drawn in the screen's text colour, dark pixels stay background.
Images smaller than 68x140 are centred horizontally and placed per --align.
"""
import argparse
from pathlib import Path
from PIL import Image

W, H = 68, 140
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "boards/shields/nice_view_doom/widgets/art.c"


def load(path, align):
    src = Image.open(path).convert("L")
    if src.width > W or src.height > H:
        raise SystemExit(f"{path}: {src.width}x{src.height} is larger than {W}x{H}")
    art = Image.new("L", (W, H), 0)
    x = (W - src.width) // 2
    y = {"top": 0, "center": (H - src.height) // 2, "bottom": H - src.height}[align]
    art.paste(src.point(lambda v: 255 if v >= 128 else 0), (x, y))
    return art


def image_c(name, art):
    # Stored rotated like the stock nice!view art: screen "up" is +x of the 140x68 buffer.
    land = art.rotate(-90, expand=True)
    stride = (land.width + 7) // 8
    data = []
    for y in range(land.height):
        for bx in range(stride):
            byte = 0
            for bit in range(8):
                x = bx * 8 + bit
                # bit 1 = palette index 1 = background, as in the stock art
                if x < land.width and land.getpixel((x, y)) < 128:
                    byte |= 1 << (7 - bit)
            data.append(byte)
    rows = ",\n        ".join(", ".join(f"0x{b:02x}" for b in data[i:i + 15])
                              for i in range(0, len(data), 15))
    return f"""
const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {name}_map[] = {{
#if CONFIG_NICE_VIEW_DOOM_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

        {rows},
}};

const lv_img_dsc_t {name} = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {land.width},
    .header.h = {land.height},
    .data_size = {len(data) + 8},
    .data = {name}_map,
}};
"""


def to_c(images):
    sources = ", ".join(f"{name} <- {src}" for name, src, _ in images)
    return f"""/*
 * Right-hand nice!view art ({sources}).
 * Generated by scripts/nice_view_art.py - edit the PNGs, not this file.
 * SPDX-License-Identifier: MIT
 */

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif
""" + "".join(image_c(name, art) for name, _, art in images)


def preview(art, path):
    """Whole screen as seen on the keyboard: 20 px status strip on top, art below."""
    fg, bg = 236, 32
    screen = Image.new("L", (W, 160), bg)
    # mock battery and link icons in the status strip
    for x in range(40, 62):
        for y in (4, 13):
            screen.putpixel((x, y), fg)
    for y in range(4, 14):
        screen.putpixel((40, y), fg)
        screen.putpixel((61, y), fg)
    for y in range(7, 11):
        screen.putpixel((62, y), fg)
    for x in range(42, 56):
        for y in range(6, 12):
            screen.putpixel((x, y), fg)
    screen.paste(art.point(lambda v: fg if v else bg), (0, 20))
    screen.resize((W * 5, 160 * 5), Image.NEAREST).save(path)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("images", nargs="+", metavar="NAME=PNG[:align]")
    ap.add_argument("--preview", metavar="DIR")
    args = ap.parse_args()
    images = []
    for spec in args.images:
        name, rest = spec.split("=", 1)
        path, _, align = rest.partition(":")
        images.append((name, Path(path).as_posix(), load(path, align or "center")))
    OUT.write_text(to_c(images))
    if args.preview:
        for name, _, art in images:
            preview(art, Path(args.preview) / f"{name}.png")
    print("wrote", OUT.relative_to(ROOT), "with", ", ".join(n for n, _, _ in images))
